<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SecureChat.Web</AssemblyName>
    <RuntimeIdentifiers>win-x64;linux-x64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup Condition="'$(RuntimeIdentifier)' == 'win-x64'">
    <Content Include="..\..\out\build\x64-release\native.dll" Link="native.dll" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\out\build\x64-release\datachannel.dll" Link="datachannel.dll" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\out\build\x64-release\juice.dll" Link="juice.dll" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\out\build\x64-release\libcrypto-3-x64.dll" Link="libcrypto-3-x64.dll" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\out\build\x64-release\libssl-3-x64.dll" Link="libssl-3-x64.dll" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup Condition="'$(RuntimeIdentifier)' == 'linux-x64'">
    <Content Include="..\..\out\build\x64-linux-release\libnative.so" Link="libnative.so" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="wwwroot\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
