// 命令行 Host 入口。它连接已有 Server，并作为第一个聊天成员创建房间。
#include "console_utils.hpp"
#include "cert_generation.hpp"
#include "host_session_core.hpp"
#include "pki_application.hpp"
#include "relay_pool.hpp"

#include <atomic>
#include <chrono>
#include <csignal>
#include <filesystem>
#include <iostream>
#include <memory>
#include <string>
#include <stdexcept>
#include <thread>
#include <vector>

namespace {
std::atomic_bool gStopRequested = false;

void handleStopSignal(int) {
    // 信号处理器必须保持简单；只设置原子标志，让主循环自行停止。
    gStopRequested.store(true);
}

ChatCallbacks consoleCallbacks() {
    // CLI 前端只打印 native 事件；GUI/Web 前端会安装不同回调。
    ChatCallbacks callbacks;
    callbacks.onLog = [](const std::string& message) { std::cout << "[log] " << message << std::endl; };
    callbacks.onError = [](const std::string& message) { std::cerr << "[error] " << message << std::endl; };
    callbacks.onMessage = [](const std::string& message) { std::cout << "[message] " << message << std::endl; };
    callbacks.onImage = [](const std::string& message) { std::cout << "[image] " << message << std::endl; };
    callbacks.onFile = [](const std::string& message) { std::cout << "[file] " << message << std::endl; };
    callbacks.onVoice = [](const std::string& message) { std::cout << "[voice] " << message << std::endl; };
    callbacks.onStatus = [](const std::string& message) { std::cout << "[status] " << message << std::endl; };
    callbacks.onRelayStatus = [](const std::string& message) { std::cout << "[relay] " << message << std::endl; };
    return callbacks;
}

void printUsage() {
    std::cerr << "Usage:\n";
    std::cerr << "  host --room-dir <dir> [username] [--nickname <name>] [--key-pass <pass>] [--daemon]\n";
    std::cerr << "Commands: /nickname [name], /image <path>, /file <path>, /to <fingerprint-prefix> <text|attachment-command>, /list, /stop_session, /exit\n";
    std::cerr << "Options:\n";
    std::cerr << "  --daemon keeps the room running without reading stdin.\n";
    std::cerr << "  --room-dir loads room token, PKI files, and relay pool generated by cert.exe.\n";
}

bool hasDaemonFlag(const std::vector<std::string>& args) {
    // Host 默认前台运行；daemon 模式必须显式指定。
    for (std::size_t i = 1; i < args.size(); ++i) {
        if (args[i] == "--daemon") return true;
    }
    return false;
}

std::string optionValue(const std::vector<std::string>& args, const std::string& flag) {
    for (std::size_t i = 1; i + 1 < args.size(); ++i) {
        if (args[i] == flag) return args[i + 1];
    }
    return "";
}

std::vector<std::string> positionalArgs(const std::vector<std::string>& args) {
    // 移除选项，使剩余参数只包含程序名和可选用户名。
    std::vector<std::string> positional;
    positional.reserve(args.size());
    for (std::size_t i = 0; i < args.size(); ++i) {
        if (args[i] == "--daemon") continue;
        if (args[i] == "--room-dir" || args[i] == "--key-pass" || args[i] == "--nickname") {
            ++i;
            continue;
        }
        positional.push_back(args[i]);
    }
    return positional;
}

void waitForDaemonStop(const std::shared_ptr<HostSessionCore>& session) {
    // daemon 模式没有 stdin 循环；它会等待信号或会话关闭。
    std::signal(SIGINT, handleStopSignal);
    std::signal(SIGTERM, handleStopSignal);

    std::cout << "Daemon mode enabled. Stop with SIGTERM, SIGINT, or kill <pid>." << std::endl;
    while (!gStopRequested.load() && !session->shouldStop()) {
        std::this_thread::sleep_for(std::chrono::milliseconds(300));
    }
}

void runExternalServerSession(
    const std::shared_ptr<HostSessionCore>& session,
    const std::string& roomId,
    const std::string& relayUrl,
    bool daemonMode) {
    // 前台和 daemon Host 共用的循环。会话对象拥有所有 WebSocket、PKI、
    // group-key 和中继状态。
    session->setCallbacks(consoleCallbacks());
    session->start();

    std::cout << "Hosting " << roomId << " through relay " << relayUrl << std::endl;
    if (daemonMode) {
        waitForDaemonStop(session);
    }
    else {
        std::string line;
        bool inputClosed = false;
        while (!session->shouldStop()) {
            if (!readInputLineUtf8(line)) {
                inputClosed = true;
                break;
            }
            if (line == "/exit") break;
            session->sendLine(line);
        }
        if (inputClosed && !session->shouldStop()) {
            std::cout << "[status] Console input closed; stopping host" << std::endl;
        }
    }

    session->stop();
}
}

int main(int argc, char** argv) {
    // CLI main 只负责连接参数、房间证书目录、回调和会话循环。
    // 协议工作位于 HostSessionCore 内部。
    configureConsoleUtf8();
    const auto rawArgs = commandLineArgsUtf8(argc, argv);
    const auto daemonMode = hasDaemonFlag(rawArgs);
    const auto roomDir = optionValue(rawArgs, "--room-dir");
    const auto keyPassword = optionValue(rawArgs, "--key-pass");
    const auto nickname = optionValue(rawArgs, "--nickname");
    const auto args = positionalArgs(rawArgs);
    if (roomDir.empty() || args.size() > 2) {
        printUsage();
        return 1;
    }

    try {
        const auto requestedUser = args.size() > 1 ? args[1] : std::string();
        const auto material = chat::certs::loadRoomRuntimeMaterial(roomDir, requestedUser, true);
        auto identity = chat::pki_application::loadFromFiles(
            material.trustStoreFile,
            material.identityCertFile,
            material.identityKeyFile,
            keyPassword);
        const auto relayUrl = chat::relay_pool::primaryRelayUrlFromRoomDir(std::filesystem::path(roomDir));
        auto session = std::make_shared<HostSessionCore>(
            relayUrl,
            material.roomName,
            material.username,
            material.baseUsername,
            nickname,
            std::move(identity),
            material.roomInstanceToken,
            roomDir);
        const auto roomId = material.roomName;
        runExternalServerSession(session, roomId, relayUrl, daemonMode);
        return 0;
    }
    catch (const std::exception& e) {
        std::cerr << "[fatal] " << e.what() << std::endl;
        return 1;
    }
}
